#!/bin/sh
if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
	. /etc/rc.conf
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh
		CONFIGLOADED="1"
	fi
fi

case "$1" in
	start)
		#start
		. /etc/rc.d/init.d/algs_start
		;;
	stop)
		#stop
		. /etc/rc.d/init.d/algs_stop
		;;
	restart)
		#restart
		. /etc/rc.d/init.d/algs_stop
		. /etc/rc.d/init.d/algs_start
		;;
	*)
		echo $"Usage $0 {start|stop|restart}"
		exit 1
esac

exit $?
