#!/bin/sh

# Nirav.
# The new inetd service entry is as given below.
# service stream/dgram protocol wait/nowait user service_name service_class interface_to_listen socket_options path arguments
#	service_name : This is the unique name of the service. When inetd.conf contains mulitiple service entries with the same service_name,
#					it spawns only one of them when the request is received for any one of the service. The other service socket are closed 
#					by inetd and it is the responsibility of the spawned process to open the remaining socket. e.g. http (service_name) 
#					with httpd(service_port) and cli(service_port)
#	serive_class : This is the unique class of the service. When inetd.conf contains mulitiple service entries with the same service_class,
#					it spawns only one of them when the request is received for any one of the service. For the other service request, inetd 
#					declines the access saying "Similar services are currently running". e.g. tftp and ftp.

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		. /etc/rc.conf
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh
		CONFIGLOADED="1"
	fi
fi

	INETD_START_FLAG="0"
	echo -n > /ramdisk/etc/inetd.conf
	if  [ "$IFX_CONFIG_TFTP_SERVER" = "1" ]; then
		if [ "$TFTP_WAN_ENABLE" = "1" -o "$TFTP_LAN_ENABLE" = "1" ]; then 
			#echo "tftp	dgram	udp	wait	root	/usr/sbin/tftpd	/usr/sbin/tftpd -p -c -u root -s /ramdisk/tftp_upload" >> /ramdisk/etc/inetd.conf
			echo "tftp	dgram	udp	wait	root	tftp	ifxftp	-	-	/usr/sbin/tftpd	/usr/sbin/tftpd -p -c -u root -s /ramdisk/tftp_upload" >> /ramdisk/etc/inetd.conf
			INETD_START_FLAG="1"
		fi
	fi
	if  [ "$IFX_CONFIG_TELNET_SERVER" = "1" ]; then
		if [ "$TELNET_WAN_ENABLE" = "1" -o "$TELNET_LAN_ENABLE" = "1" ]; then
			#echo "telnet	stream	tcp	nowait	root	/usr/sbin/telnetd	telnetd" >> /ramdisk/etc/inetd.conf
			echo "telnet	stream	tcp	wait	root	telnet	ifxrcon	-	-	/usr/sbin/telnetd	telnetd" >> /ramdisk/etc/inetd.conf
			INETD_START_FLAG="1"
		fi
	fi
	if  [ "$IFX_CONFIG_SSH_SERVER" = "1" ]; then
		if [ "$SSH_WAN_ENABLE" = "1" -o "$SSH_LAN_ENABLE" = 1 ]; then
			if [ ! -s /tmp/rsa_key ]; then
				/usr/bin/dropbearkey -t rsa -f /tmp/rsa_key 
			fi
			#echo "ssh	stream	tcp	nowait	root	/usr/sbin/dropbear	dropbear -i -r /tmp/rsa_key" >> /ramdisk/etc/inetd.conf
			echo "ssh	stream	tcp	nowait	root	sshd	ifxrcon	-	-	/usr/sbin/dropbear	dropbear -i -r /tmp/rsa_key" >> /ramdisk/etc/inetd.conf
			INETD_START_FLAG="1"
		fi
	fi

	if  [ "$IFX_CONFIG_FTP_SERVER" = "1" ]; then
		if [ "$FTP_WAN_ENABLE" = "1" -o "$FTP_LAN_ENABLE" = "1" ]; then
			#echo "ftp	stream	tcp	nowait	root	/usr/sbin/ftpd /usr/sbin/ftpd" >> /ramdisk/etc/inetd.conf
			echo "ftp	stream	tcp	nowait	root	ftpd	ifxftp	-	-	/usr/sbin/ftpd /usr/sbin/ftpd" >> /ramdisk/etc/inetd.conf
			INETD_START_FLAG="1"
		fi
	fi

	if  [ "$IFX_CONFIG_WEB_SERVER" = "1" ]; then
		if [ "$WEB_WAN_ENABLE" = "1" -o "$WEB_LAN_ENABLE" = "1" ]; then
			if [ "$IFX_CONFIG_CLI" = "1" ]; then
				echo "httpd	stream tcp wait	root httpd ifxhttpd - - /usr/sbin/httpd httpd -h /usr/web -H /usr/cli -A httpd" >> /ramdisk/etc/inetd.conf
				echo "/tmp/cli_be_socket stream unix wait root httpd ifxhttpd - - /usr/sbin/httpd httpd -h /usr/web -H /usr/cli -A cli" >> /ramdisk/etc/inetd.conf
			else
				echo "httpd	stream tcp wait	root httpd ifxhttpd - - /usr/sbin/httpd httpd -h /usr/web -A httpd" >> /ramdisk/etc/inetd.conf
			fi
			INETD_START_FLAG="1"
		fi
	fi
	
	if [ "$IFX_CONFIG_CLI" = "1" ]; then
			echo "/tmp/cli_fe_socket stream unix wait root cli ifxcli - - /usr/sbin/cli_be" >> /ramdisk/etc/inetd.conf
			INETD_START_FLAG="1"
	fi

	if  [ "$IFX_CONFIG_DHCP_SERVER" = "1" ]; then
		if [ "$lan_dhcp_mode" = "server" ]; then
			if [ -f /etc/udhcpd.conf ]; then
				echo "udhcpd dgram udp wait root udhcpd ifxudhcpd $lan_interface BROADCAST /usr/sbin/udhcpd udhcpd" >> /ramdisk/etc/inetd.conf
				INETD_START_FLAG="1"
			fi
		fi
	fi

	if  [ "$IFX_CONFIG_DHCP_SERVER" = "1" ]; then
		if [ "$lan_dhcp_mode" = "relay" ]; then
			if [ -f /tmp/udhcprconfig.txt ]; then
				cat /tmp/udhcprconfig.txt >> /ramdisk/etc/inetd.conf
				INETD_START_FLAG="1"
			fi
		fi
	fi
	#start inetd superserver
	if [ "$INETD_START_FLAG" = "1" ]; then
		if [ -f /var/run/inetd.pid ]; then
			#The server is already running and so just send HUP singal
			inetdpid=`cat /var/run/inetd.pid`
			kill -HUP $inetdpid
		else
			#The server is not running and so start it
			/usr/sbin/inetd /etc/inetd.conf
		fi
	fi

