#!/bin/sh
# 000001:tc.chen 2005/06/07 add 802.1p and ip ptos support. rewrite all of the qos scirpts

if [ ! "$ENVLOADED" ]; then
	if [ -r /etc/rc.conf ]; then
		. /etc/rc.conf
		ENVLOADED="1"
	fi
fi

if [ ! "$CONFIGLOADED" ]; then
	if [ -r /etc/rc.d/config.sh ]; then
		. /etc/rc.d/config.sh
		CONFIGLOADED="1"
	fi
fi

# 000001:tc.chen remove start
## WAN="`/etc/rc.d/get_wan_if $1`"
#
#LAN="`/etc/rc.d/get_lan_if`"
#
##waiting for showtime
#while [ -z `/bin/cat /tmp/adsl_status | grep "7"` ]; do
#    sleep 1
#done
#
## totol downstream bandwidth in KBytes
#DOWNSTREAM="`/usr/sbin/get_adsl_rate 1`"
#
## total upstream bandwidth in KBytes
#UPSTREAM="`/usr/sbin/get_adsl_rate 0`"
#
## Ration in %
#BANDWIDTH_RATIO=80
#DOWNSTREAM=`expr $DOWNSTREAM \* $BANDWIDTH_RATIO / 100`
#UPSTREAM=`expr $UPSTREAM \* $BANDWIDTH_RATIO / 100`
#
## IMQ device name
#DS_DEV_0=imq0
#DS_DEV_1=imq1
#DS_DEV_2=imq2
#
##start() {
#	insmod imq numdevs=3
#	if [ "$DIFFSERV_VIRTUAL_SERVER" = "1" ]; then
#		LAN_OTHER_CLASS_ID=`expr $NATVS_NUM + 2`
#		# incoming packets from LAN
#		tc qdisc add dev $DS_DEV_2 handle 1: root htb default $LAN_OTHER_CLASS_ID
#		tc class add dev $DS_DEV_2 parent 1: classid 1:1 htb rate ${UPSTREAM}kbps
#		others_bandwidth=0
#		i=1
#		while [ "$i" -ge 1 -a "$i" -le $NATVS_NUM ]
#		do
#			eval NATVS_PTYPE='$NATVS_PTYPE'${i}
#			eval NATVS_PIP='$NATVS_PIP'${i}
#			eval NATVS_PPORT='$NATVS_PPORT'${i}
#			eval NATVS_F='$NATVS_F'${i}
#			eval NATVS_QOS_ENABLE='$NATVS_QOS_ENABLE'${i}
#			eval NATVS_MIN_BW='$NATVS_MIN_BW'${i}
#			eval NATVS_MAX_BW='$NATVS_MAX_BW'${i}
#			if [ "$NATVS_F" = "1" -a "$NATVS_QOS_ENABLE" = "1" ]; then
#				LAN_CLASS_ID=`expr $i + 1`
#				others_bandwidth=`expr $others_bandwidth + $NATVS_MIN_BW`
##				NATVS_MAX_BW=`expr $UPSTREAM \* $NATVS_MAX_BW / 100`
#				tc class add dev $DS_DEV_2 parent 1:1 classid 1:${LAN_CLASS_ID} htb rate ${NATVS_MIN_BW}kbps ceil ${NATVS_MAX_BW}kbps cburst 10500 quantum 3000
#				tc qdisc add dev $DS_DEV_2 parent 1:${LAN_CLASS_ID} handle ${LAN_CLASS_ID}0: pfifo limit 20
##			fi
#			i=`expr $i + 1`
#		done
#		others_bandwidth=`expr 100 - $others_bandwidth`
#		others_bandwidth=`expr $UPSTREAM \* $others_bandwidth / 100`
#		tc class add dev $DS_DEV_2 parent 1:1 classid 1:${LAN_OTHER_CLASS_ID} htb rate ${others_bandwidth}kbps ceil ${UPSTREAM}kbps cburst 10500 quantum 1500
#		tc qdisc add dev $DS_DEV_2 parent 1:${LAN_OTHER_CLASS_ID} handle ${LAN_OTHER_CLASS_ID}0: pfifo limit 20
#		ifconfig $DS_DEV_2 up
#	fi
#	if [ "$DIFFSERV_DUT_VOIP" = "1" ]; then
#		# Incoming packets from WAN
#		SERVICE_VOIP=10
#		SERVICE_OTHERS=10
#		VOICE_MIN_BW=`expr $DOWNSTREAM \* $SERVICE_VOIP / 100`
#		VOICE_MAX_BW=$DOWNSTREAM
#		VOICE_QLENGTH=50
#		OTHER_MIN_BW=`expr $DOWNSTREAM \* $SERVICE_OTHERS / 100`
#		OTHER_MAX_BW=$DOWNSTREAM
#		OTHER_QLENGTH=100
#		tc qdisc add dev $DS_DEV_0 handle 1: root htb default 3
#		tc class add dev $DS_DEV_0 parent 1:0 classid 1:1 htb rate ${DOWNSTREAM}kbps
#		tc class add dev $DS_DEV_0 parent 1:1 classid 1:2 htb rate ${VOICE_MIN_BW}kbps ceil ${VOICE_MAX_BW}kbps cburst 5500 quantum 3000 prio 0
#		tc class add dev $DS_DEV_0 parent 1:1 classid 1:3 htb rate ${OTHER_MIN_BW}kbps ceil ${OTHER_MAX_BW}kbps cburst 10500 quantum 1500 prio 1
#		tc qdisc add dev $DS_DEV_0 parent 1:2 handle 20: pfifo limit $VOICE_QLENGTH
#		tc qdisc add dev $DS_DEV_0 parent 1:3 handle 30: pfifo limit $OTHER_QLENGTH
#		tc filter add dev $DS_DEV_0 parent 1: protocol ip handle 1 fw classid 1:2
#		ifconfig $DS_DEV_0 up
#		tc qdisc add dev $DS_DEV_1 handle 1: root dsmark indices 2
#		tc class change dev $DS_DEV_1 parent 1:0 classid 1:1 dsmark mask 0x0 value 0xb8
#		ifconfig $DS_DEV_1 up
#	fi 
# 000001:tc.chen remove

# 000001:tc.chen start
#initial mangle 
iptables -t mangle -N QOS_PREROUTING
iptables -t mangle -N QOS_VS
iptables -t mangle -N QOS_PRIO
iptables -t mangle -A QOS_PREROUTING -j QOS_VS
iptables -t mangle -A QOS_PREROUTING -j QOS_PRIO
iptables -t mangle -N QOS_POSTROUTING

if [ "$QOS_ENABLE" = 1 ]; then
	/etc/rc.d/init.d/qos_start
	if [ "$QOS_PRIO" = "1" ]; then
#509023:linmars start
		/etc/rc.d/init.d/pif start
#509023:linmars end
		/etc/rc.d/init.d/qos_apply_priority
	fi
fi
# 000001:tc.chen end
