#!/bin/sh

#start() {
#	/usr/sbin/tftpd -l -c -u root -s /ramdisk/tftp_upload > /dev/null 2>&1 &
#}
#
#stop() {
#	rm -f /ramdisk/tftp_upload/*
#	killall tftpd 
#}


case "$1" in
	start)
		#start
		/usr/sbin/tftpd -l -c -u root -s /ramdisk/tftp_upload > /dev/null 2>&1 &
		;;
	stop)
		#stop
		rm -f /ramdisk/tftp_upload/*
		killall tftpd 
		;;
esac

exit $?
