#!/bin/sh

. ./Path.sh
. ./config.sh

IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS networkprocessor"

if  [ $IFX_CONFIG_ALGS -a $IFX_CONFIG_ALGS = "1" ]; then
	IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS nfappcfg"
	IFX_CONFIG_IPTABLES="1"
fi

if  [ $IFX_CONFIG_ADSL_FIRMWARE_LOADER -a $IFX_CONFIG_ADSL_FIRMWARE_LOADER = "1" ]; then
	IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS adsl_firmware_loader"
fi

if  [ $IFX_CONFIG_TR037 -a $IFX_CONFIG_TR037 = "1" ]; then
	IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS ilmid"
fi

if  [ $IFX_CONFIG_OAM -a $IFX_CONFIG_OAM = "1" ]; then
	IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS oam"
fi

# 606261:fchang.added.start support VDSL2_Vinax driver
if  [ $IFX_CONFIG_VDSL2 -a $IFX_CONFIG_VDSL2 = "1" ]; then
        IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS vdsl2"
fi
# 606261:fchang.added.end

# 605261:fchang.added.start support Atheros driver
if  [ $IFX_CONFIG_WIRELESS -a $IFX_CONFIG_WIRELESS = "1" ]; then
        #IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS atheros_wireless"
        IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS atheros_wireless/802_11/madwifi"
        IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS atheros_wireless/802_11/dual_core"
fi
# 605261:fchang.added.end
# 2006/6/20 winder remove linux-atm-2.4.1 part.
OPENSOURCE_APPS_SUBDIRS="mtd bridge-utils busybox-1.00"

if  [ $IFX_CONFIG_NTPCLIENT -a $IFX_CONFIG_NTPCLIENT = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS ntpclient"
fi

if  [ $IFX_CONFIG_MULTIPLE_VCCS -a $IFX_CONFIG_MULTIPLE_VCCS = "1" ]; then
	echo IFX_CONFIG_MULTIPLE_VCCS
fi

if  [ $IFX_CONFIG_PPPOE_RELAY -a $IFX_CONFIG_PPPOE_RELAY = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS rp-pppoe-3.5"
fi

if  [ $IFX_CONFIG_PPPOE -a $IFX_CONFIG_PPPOE = "1" ]; then
	IFX_CONFIG_PPPD="1"
fi

if  [ $IFX_CONFIG_PPPOA -a $IFX_CONFIG_PPPOA = "1" ]; then
	IFX_CONFIG_PPPD="1"
fi

if [ $IFX_CONFIG_PPPD -a $IFX_CONFIG_PPPD = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS ppp-2.4.2"
fi

if  [ $IFX_CONFIG_RFC2684 -a $IFX_CONFIG_RFC2684 = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS br2684ctl-20040226-1"
fi

if [ $IFX_CONFIG_DHCP_RELAY -a $IFX_CONFIG_DHCP_RELAY = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS dhcp-3.0.1rc14"
fi

if  [ $IFX_CONFIG_DNSRELAY -a $IFX_CONFIG_DNSRELAY = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS dnrd-2.19"
fi

if  [ $IFX_CONFIG_DDNS -a $IFX_CONFIG_DDNS = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS ez-ipupdate-3.0.11b8"
fi

if  [ $IFX_CONFIG_WIRELESS -a $IFX_CONFIG_WIRELESS = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="wireless_tools.27 $OPENSOURCE_APPS_SUBDIRS"
fi

if  [ $IFX_CONFIG_SNMPv1 -a $IFX_CONFIG_SNMPv1 = "1" ]; then
	IFX_CONFIG_SNMP_AGENT="1"
fi

if  [ $IFX_CONFIG_SNMPv3 -a $IFX_CONFIG_SNMPv3 = "1" ]; then
	IFX_CONFIG_SNMP_AGENT="1"
	IFX_CONFIG_OPENSSL="1"
fi

if  [ $IFX_CONFIG_EBTABLES -a $IFX_CONFIG_EBTABLES = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS ebtables-v2.0.6"
fi

if  [ $IFX_CONFIG_FIREWALL -a $IFX_CONFIG_FIREWALL = "1" ]; then
	IFX_CONFIG_IPTABLES="1"
fi

if  [ $IFX_CONFIG_NAPT -a $IFX_CONFIG_NAPT = "1" ]; then
	IFX_CONFIG_IPTABLES="1"
fi

if [  $IFX_CONFIG_IPTABLES -a $IFX_CONFIG_IPTABLES = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS iptables-1.2.9"
fi

if  [ $IFX_CONFIG_RIP -a  $IFX_CONFIG_RIP = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS zebra-0.94"
fi

if  [ $IFX_CONFIG_WEB_SERVER -a $IFX_CONFIG_WEB_SERVER = "1" ]; then
	IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS ifx_httpd"
	if [ "$IFX_CONFIG_CLI" = "1" ]; then
		IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS ifx_cli"
	fi
fi

if  [ $IFX_CONFIG_SWMOD -a $IFX_CONFIG_SWMOD = "1" ]; then
	IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS swmod"
fi

if  [ $IFX_CONFIG_TFTP_SERVER -a $IFX_CONFIG_TFTP_SERVER = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS tftp-hpa-0.40"
fi

if  [ $IFX_CONFIG_FTP_SERVER -a $IFX_CONFIG_FTP_SERVER = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS linux-ftpd-0.17"
fi

if  [ $IFX_CONFIG_SSH_SERVER -a $IFX_CONFIG_SSH_SERVER = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS dropbear-0.43"
fi

if  [ $IFX_CONFIG_DSL_MANAGEMENT -a $IFX_CONFIG_DSL_MANAGEMENT = "1" ]; then
	IFX_CONFIG_SNMP_AGENT="1"
fi

if  [ $IFX_VLAN_SUPPORT -a $IFX_VLAN_SUPPORT = "1" ]; then
	IFX_APPS_SUBDIRS="$IFX_APPS_SUBDIRS nfext"
fi

if  [ $IFX_CONFIG_OPENSSL -a $IFX_CONFIG_OPENSSL = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS openssl-0.9.7d"
fi

if [  $IFX_CONFIG_SNMP_AGENT -a $IFX_CONFIG_SNMP_AGENT = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS net-snmp-5.1"
fi

if [  $IFX_CONFIG_SYSSTAT -a $IFX_CONFIG_SYSSTAT = "1" ]; then
        OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS sysstat-6.0.1"
fi

if  [ $IFX_CONFIG_QOS -a $IFX_CONFIG_QOS = "1" ]; then
	OPENSOURCE_APPS_SUBDIRS="$OPENSOURCE_APPS_SUBDIRS iproute2"
fi

echo =========================
echo $IFX_APPS_SUBDIRS
echo " Modules : "$OPENSOURCE_APPS_SUBDIRS
echo =========================

