#!/bin/sh

if [ -z "$ifconfig_lan" ]; then
	if [ ! "$ENVLOADED" ]; then
		if [ -r /etc/rc.conf ]; then
			. /etc/rc.conf
			ENVLOADED="1"
		fi
	fi

	if [ ! "$CONFIGLOADED" ]; then
		if [ -r /etc/rc.d/config.sh ]; then
			. /etc/rc.d/config.sh
			CONFIGLOADED="1"
		fi
	fi
fi

eval wan_type='$'ipoption_wan$1
eval ATMPROTO='$'ATM_PROTOCOL$1

#Public variable
if [ "$wan_type" = "DHCPC" ]; then
        WAN="nas$1"
elif [ "$wan_type" = "FIXED" ]; then
        if [ "`echo $ATMPROTO |cut -b-7`" = "rfc2684" ]; then
        WAN="nas$1"
        elif [ "$ATMPROTO" = "clip" ]; then
        WAN="atm$1"
        fi
elif [ "$wan_type" = "PPPOE" ]; then
#		if [ -f /var/run/ppp-pppoe-$1.pid ]; then
#        WAN="`cat /var/run/ppp-pppoe-$1.pid |grep ppp`"
#		fi
	WAN="ppp$1"
elif [ "$wan_type" = "PPPOA" ]; then
#		if [ -f /var/run/ppp-pppoatm-$1.pid ]; then
#        WAN="`cat /var/run/ppp-pppoatm-$1.pid |grep ppp`"
#		fi
	WAN="ppp$1"
elif [ "$wan_type" = "TR037" ]; then
        if [ "$TR037_PROTO" = "PPPOA" ]; then
                WAN="ppp$1"
else
                WAN="nas$1"
        fi
else
        WAN="br0"
fi
echo $WAN
