#!/bin/sh

	if [ -f /var/run/$1.pid ]; then
#		read line < /var/run/$1.pid
		line=`cat /var/run/$1.pid | cut -f1 -d' '`
		for p in $line; do
			pid="$pid $p"
		done
	fi
	echo "pid = $pid"
	if [ -z "$pid" ]; then
		/usr/bin/killall $1
	else
		kill -TERM $pid
		usleep 100000
		if /etc/rc.d/checkpid $pid && sleep 1 &&
		   /etc/rc.d/checkpid $pid $$ sleep 3 &&
		   /etc/rc.d/checkpid $pid; then
			kill -KILL $pid
			usleep 100000
		fi
	fi
	rm -f /var/run/$1.pid
